# ███╗   ███╗ █████╗ ██████╗ ██████╗ ███████╗██╗
# ████╗ ████║██╔══██╗██╔══██╗██╔══██╗██╔════╝██║
# ██╔████╔██║███████║██████╔╝██████╔╝█████╗  ██║
# ██║╚██╔╝██║██╔══██║██╔══██╗██╔══██╗██╔══╝  ██║
# ██║ ╚═╝ ██║██║  ██║██║  ██║██████╔╝███████╗███████╗
# ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝


trigger:
  branches:
    exclude:
      - main  

parameters:
- name: cleanDirectory
  type: boolean
  default: true  

variables:
  solutionName: 'src'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  filePowerBiPath: '$(workingDirectory)\$(solutionName)\pbix'  
  filePowerBiName: 'PBIDaysMalagaReport.pbix'
  filePowerBi: '$(filePowerBiPath)\$(filePowerBiName)'
  tmpDirectoryPath: '$(filePowerBiPath)\tmp'
  extractDirectoryPath: '$(filePowerBiPath)\extract'
  pbitoolUrlVersion: 'https://github.com/pbi-tools/pbi-tools/releases/download/1.0.0-rc.4/pbi-tools.1.0.0-rc.4.zip'

pool:
  name: 'agentPool'

steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - powershell: |
      $SourceBranch = "$(Build.SourceBranch)".Replace("refs/heads/", "")

      Write-Host "Git configuration"
      git config --global user.email "$(Build.RequestedForEmail)"
      git config --global user.name "(Build.RequestedFor)"
      
      Write-Host "Change branch"
      git checkout -b $SourceBranch
    displayName: 'Git config'
    enabled: true

  - task: PowerShell@2
    displayName: 'Download & Install - PBI-tools'
    enabled: true
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      pwsh: true
      targetType: 'inline'
      script: |
        Invoke-WebRequest -Uri $(pbitoolUrlVersion) -OutFile pbitools.zip
        Expand-Archive -Path "$(System.DefaultWorkingDirectory)/pbitools.zip" -DestinationPath "$(System.DefaultWorkingDirectory)"

  - task: PowerShell@2
    displayName: 'Download & Install - PowerBI'
    enabled: true
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      pwsh: true
      targetType: 'inline'
      script: |
        choco install powerbi --ignore-checksums -y

  - task: PowerShell@2
    displayName: 'PBITool - Extract PBIX'
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      pwsh: true
      targetType: 'inline'
      script: |
        .\pbi-tools.exe extract -pbixPath "$(filePowerBi)" -extractFolder "$(tmpDirectoryPath)"

  - task: PublishPipelineArtifact@1
    displayName: 'Upload PBIX-Json Files - Artifact'
    inputs:
      targetPath: '$(tmpDirectoryPath)'
      artifact: 'PBIX-JSON'

  - task: DeleteFiles@1
    displayName: 'Clean directory'
    condition: and(succeeded(), eq(${{parameters.cleanDirectory}}, true))
    inputs:
      sourceFolder: '$(extractDirectoryPath)'
      contents: '**'
      removeSourceFolder: false

  - task: CopyFiles@2
    displayName: 'Copy files'
    inputs:
      SourceFolder: '$(tmpDirectoryPath)'
      Contents: '**'
      TargetFolder: '$(extractDirectoryPath)'
      OverWrite: true

  - powershell: |
      $SourceBranch = "$(Build.SourceBranch)".Replace("refs/heads/", "")
      $SourceBranchHead = "$(Build.SourceBranch)"
      $TmpFilesPath = "$(tmpDirectoryPath)"
      $ExtractFilesPath = "$(extractDirectoryPath)"

      Write-Host "Git configuration"
      git config --global user.email "$(Build.RequestedForEmail)"
      git config --global user.name "(Build.RequestedFor)"

      Write-Host "Git show Branch"
      git branch

      Write-Host "Git add"
      git add $ExtractFilesPath\*

      Write-Host "git commit"
      git commit -m "Updated PBIX extract files [ci skip]" 
      
      Write-Host "Git push"
      git push -u origin $SourceBranch
    displayName: 'Update PBIX Json'
    enabled: true